[
  ["sntp", "o", {title: "SNTP settings"}],
  ["sntp.enable", "b", true, {title: "Enable SNTP"}],
  ["sntp.server", "s", "time.google.com", {title: "Server address"}],
  ["sntp.retry_min", "i", 1, {title: "Minimum retry interval"}],
  ["sntp.retry_max", "i", 30, {title: "Maximum retry interval"}],
  ["sntp.update_interval", "i", 7200, {title: "Update interval. If 0, performs a one-off sync"}],
]
